# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://shinede.github.io/
#date_format: "ordinal"
title: 记录 --Me开发编程中的点点滴滴
#tip blog头部标题
tip: 记录
subtitle: "记录、代码上的那些事"
description: "ShienDe的个人博客，记录，编程，开发"
keywords: 记录, Shine De, ShineDe, Ting
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ShineDe
organization: Sogou, Inc.
organization_url: https://www.sogou.com
location: ZhuHai, China
email: huangdehar@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: ShineDe
douban_username: shinede
# facebook_username: shinede
#weibo_username: mzlogin
zhihu_username: shinede
# twitter_username: mzlogin

# ---------------- #
#      Comments    #
#      注释了多少评论配置，因为多少要关闭了。    #
# ---------------- #
# support provider: disqus, duoshuo
# comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# duoshuo_username: shinede
#disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
